repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
-   repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 1.5.1
    hooks:
    -   id: forbid-binary
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    sha: v1.1.5
    hooks:
    -   id: remove-crlf
-   repo: https://github.com/willthames/ansible-lint
    sha: v3.4.21
    hooks:
    -   id: ansible-lint
