[project]
name = "osx-ansible"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ansible>=12.2.0",
    "ansible-lint>=24.0.0",
]
